#!/bin/bash
# This script runs feed.py
echo "=================================="
echo "Running Blog generator..."

# Configure Git user
git config --global user.name "${GITHUB_ACTOR}"
git config --global user.email "${INPUT_EMAIL}"

# Add safe directory to allow Git operations
git config --global --add safe.directory /github/workspace

# Run the Python application
python3 /usr/bin/feed.py

#Commit and push any files generated by feed.py (like podcast.xml) back to the repository:
# Stage all changes
git add -A

# Commit with message
git commit -m "Update feed"

# Push to main branch (set upstream if needed)
git push --set-upstream origin main

echo "=================================="
